##
# Use Exemple
# my_first_job:
#   cron: "*/1 * * * *"
#   class: "DefaultWorker"
#   queue: cron_jobs

task_trigger:
  cron: "*/1 * * * *"
  class: "TaskTrigger"

delayer_task_trigger:
  cron: "*/1 * * * *"
  class: "DelayerTaskTrigger"